### ISSUE TITLE
Small Cosmetic Problems.

### ISSUE THREAD

**Issue by LeifAndersen** [stephenjsweeney/blobwarsAttrition#13]
Here I will note several small (entirely cosmetic) problems I've noticed that do not deserve their own github issues, but should probably be fixed at some point none-the-less.

- [x] Tutorial text revers to touch screen device.
- [x] Inconsistent use of the text POWs vs MIAs. POW seems to be the most commonly used one, but several places seem to use MIA for the same purpose.
- [x] Machine gun shells fire from the right side of bob when facing left. When he's facing right it makes sense for bullets to come out of the right, but when he's facing left it looks odd and inconsistent. This might also happen on other weapons, but its much less noticeable(y distracting).

**Comment by stephenjsweeney** [comment]
I remember at the time of making the original Android version that coming the Blobs that been taken prison and locked up "MIAs" didn't make sense, so I named them POWs in some instances. I've reworked the wording so that they're all called MIAs now.

Also updated the bullet positioning so that it's now centred within the shooter.

**Comment by stephenjsweeney** [comment]
Closing, as all fixed.
