### ISSUE TITLE
Powerup stuck in wall

### ISSUE THREAD

**Issue by LeifAndersen** [stephenjsweeney/blobwarsAttrition#17]
It looks like a powerup is stuck in the wall and I can't find any way to get it or reset it to its original position. This seems to have soft-locked the game and require a restart. The level is outpost 4, at the top of the upper level floors.

<img width="1280" alt="screen shot 2018-04-28 at 10 20 09 am" src="https://user-images.githubusercontent.com/285926/39397486-f98b080c-4acd-11e8-9f4f-b7d103e238aa.png">

**Comment by stephenjsweeney** [comment]
I'm guessing this is due to returning to the level?

My guess is that's a silver key, as the cannons in that area are holding them. Any idea what happened?

A temporary solution to this is to load the save game data for outpost 4, find the affected item (I'm guessing it's a silver key), and shunting it down by increasing its y value (by 64 or 96).

Still, odd. When items are dropped, they are given the y value of the thing holding it:

https://github.com/stephenjsweeney/blobwarsAttrition/blob/master/src/world/entities.c#L1010

That would imply that the cannon itself was somehow in the wall. Or perhaps it was somehow affected by the door and ended up on top of it?

**Comment by LeifAndersen** [comment]
Yup, after further investigation its certainly a silver key. (Its the only thing left to do in the game, is get that key and place the last tnt).

I wonder if I:
1. Killed the cannon
2. While dying bounced into the teleporter
3. It finished dying in transit.
4. Thus leaving the key in the middle of the wall.

**Comment by LeifAndersen** [comment]
Where is the save game data btw? It doesn't seem to be stored in the repo, or in the ~/Library folder on os x?

**Comment by LeifAndersen** [comment]
Oh ya, looking at the error messages...

```
2018-04-28 10:32:31.998 blobwarsAttrition[54154:345666] WARN: Silver Key (9): in wall at 37,67
2018-04-28 10:35:41.896 blobwarsAttrition[54154:345666] WARN: Silver Key (9): in wall at 37,67
```

**Comment by LeifAndersen** [comment]
Never mind. I dug in the code and found it: `.local/share/blobwarsAttrition`.

**Comment by stephenjsweeney** [comment]
Could you send me the save files? Just zip that entire folder.

**Comment by LeifAndersen** [comment]
Sure, here you go:

[1.zip](https://github.com/stephenjsweeney/blobwarsAttrition/files/1957830/1.zip)

**Comment by stephenjsweeney** [comment]
Try the latest code in develop. It should now reset the key.

**Comment by LeifAndersen** [comment]
Alright, I gave it a shot and it seems to have worked. Thanks.
